Use client instead of frontend

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 # bin/detect <build-dir>
 
-if [ -f $1/../frontend/package.json ]; then
+if [ -f $1/client/package.json ]; then
   echo 'Node.js'
   exit 0
 fi
 
->&2 echo 'Node.js: package.json not found in application root'
+>&2 echo 'Node.js: package.json not found in client directory'
 exit 1
